"""initial schema - all tables and indexes

Revision ID: 274c18df8c4a
Revises: 
Create Date: 2026-03-27 14:18:13.147995
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '274c18df8c4a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archives',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('generated_at', sa.Date(), nullable=False),
    sa.Column('game_format', sa.String(length=20), nullable=False),
    sa.Column('our_deck', sa.String(length=10), nullable=False),
    sa.Column('opp_deck', sa.String(length=10), nullable=False),
    sa.Column('aggregates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('match_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_format', 'our_deck', 'opp_deck', 'generated_at')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_user', 'audit_log', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('daily_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('perimeter', sa.String(length=20), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date', 'perimeter')
    )
    op.create_index('idx_snapshots_date', 'daily_snapshots', [sa.literal_column('snapshot_date DESC')], unique=False)
    op.create_table('killer_curves',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('generated_at', sa.Date(), nullable=False),
    sa.Column('game_format', sa.String(length=20), nullable=False),
    sa.Column('our_deck', sa.String(length=10), nullable=False),
    sa.Column('opp_deck', sa.String(length=10), nullable=False),
    sa.Column('curves', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('match_count', sa.Integer(), nullable=True),
    sa.Column('loss_count', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_format', 'our_deck', 'opp_deck', 'generated_at')
    )
    op.create_index('idx_kc_lookup', 'killer_curves', ['game_format', 'our_deck', 'opp_deck', 'is_current'], unique=False, postgresql_where=sa.text('is_current = true'))
    op.create_table('matches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('game_format', sa.String(length=20), nullable=False),
    sa.Column('queue_name', sa.String(length=50), nullable=True),
    sa.Column('perimeter', sa.String(length=20), nullable=False),
    sa.Column('deck_a', sa.String(length=10), nullable=False),
    sa.Column('deck_b', sa.String(length=10), nullable=False),
    sa.Column('winner', sa.String(length=10), nullable=True),
    sa.Column('player_a_name', sa.String(length=100), nullable=True),
    sa.Column('player_b_name', sa.String(length=100), nullable=True),
    sa.Column('player_a_mmr', sa.Integer(), nullable=True),
    sa.Column('player_b_mmr', sa.Integer(), nullable=True),
    sa.Column('total_turns', sa.Integer(), nullable=True),
    sa.Column('lore_a_final', sa.Integer(), nullable=True),
    sa.Column('lore_b_final', sa.Integer(), nullable=True),
    sa.Column('turns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cards_a', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cards_b', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('idx_matches_date', 'matches', [sa.literal_column('played_at DESC')], unique=False)
    op.create_index('idx_matches_decks', 'matches', ['deck_a', 'deck_b'], unique=False)
    op.create_index('idx_matches_format', 'matches', ['game_format'], unique=False)
    op.create_index('idx_matches_lookup', 'matches', ['game_format', 'deck_a', 'deck_b', sa.literal_column('played_at DESC')], unique=False, postgresql_where=sa.text("perimeter IN ('set11', 'top', 'pro', 'friends')"))
    op.create_index('idx_matches_mmr_a', 'matches', ['player_a_mmr'], unique=False)
    op.create_index('idx_matches_mmr_b', 'matches', ['player_b_mmr'], unique=False)
    op.create_index('idx_matches_perimeter', 'matches', ['perimeter'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stripe_sub_id', sa.String(length=255), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_sub_id')
    )
    op.create_index('idx_subs_status', 'subscriptions', ['status'], unique=False)
    op.create_index('idx_subs_user', 'subscriptions', ['user_id'], unique=False)
    op.create_table('threats_llm',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('generated_at', sa.Date(), nullable=False),
    sa.Column('game_format', sa.String(length=20), nullable=False),
    sa.Column('our_deck', sa.String(length=10), nullable=False),
    sa.Column('opp_deck', sa.String(length=10), nullable=False),
    sa.Column('threats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_format', 'our_deck', 'opp_deck', 'generated_at')
    )
    op.create_table('user_decks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('deck_code', sa.String(length=10), nullable=False),
    sa.Column('cards', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_decks_user', 'user_decks', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('device_info', sa.String(length=500), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_user', 'user_sessions', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tier', sa.String(length=20), server_default='free', nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('deletion_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_tier', 'users', ['tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_tier', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_sessions_user', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('idx_user_decks_user', table_name='user_decks')
    op.drop_table('user_decks')
    op.drop_table('threats_llm')
    op.drop_index('idx_subs_user', table_name='subscriptions')
    op.drop_index('idx_subs_status', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('password_reset_tokens')
    op.drop_index('idx_matches_perimeter', table_name='matches')
    op.drop_index('idx_matches_mmr_b', table_name='matches')
    op.drop_index('idx_matches_mmr_a', table_name='matches')
    op.drop_index('idx_matches_lookup', table_name='matches', postgresql_where=sa.text("perimeter IN ('set11', 'top', 'pro', 'friends')"))
    op.drop_index('idx_matches_format', table_name='matches')
    op.drop_index('idx_matches_decks', table_name='matches')
    op.drop_index('idx_matches_date', table_name='matches')
    op.drop_table('matches')
    op.drop_index('idx_kc_lookup', table_name='killer_curves', postgresql_where=sa.text('is_current = true'))
    op.drop_table('killer_curves')
    op.drop_index('idx_snapshots_date', table_name='daily_snapshots')
    op.drop_table('daily_snapshots')
    op.drop_index('idx_audit_user', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('archives')
    # ### end Alembic commands ###
