"""widen daily_snapshots perimeter to 50 chars

Revision ID: df9cf2963a28
Revises: 274c18df8c4a
Create Date: 2026-03-27 14:24:32.428802
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'df9cf2963a28'
down_revision: Union[str, None] = '274c18df8c4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_snapshots', 'perimeter',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_snapshots', 'perimeter',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
