#!/usr/bin/env python3
"""B.6 Fase 1 — daily health digest mail.

Reads the last 24h of:
- ``user_feedback`` rows with ``status='new'``
- ``ops_incidents`` rows with ``status='new'`` AND ``severity >= warn``

Composes a single text/markdown email and sends it to MAIL_TO via the
existing Gmail SMTP wrapper (same pattern as cron_health_report.py).
On send success, marks rows as ``digested`` so the next digest doesn't
re-send them.

Cron slot suggestion: 07:30 UTC daily (after monitor_kc_freshness 07:00,
after monitor_unmapped_matches 07:05).

Usage:
    venv/bin/python3 scripts/daily_health_digest.py [--dry-run] [--mail-to addr]
"""
from __future__ import annotations

import argparse
import os
import smtplib
import sys
from datetime import datetime, timedelta, timezone
from email.mime.text import MIMEText
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from sqlalchemy import and_, func  # noqa: E402

from backend.models import SessionLocal  # noqa: E402
from backend.models.feedback import OpsIncident, UserFeedback  # noqa: E402

MAIL_FROM = os.getenv("LM_MAIL_FROM", "monitorteamfe@gmail.com")
MAIL_TO_DEFAULT = os.getenv("LM_DIGEST_MAIL_TO", "monitorteamfe@gmail.com")
SMTP_PASS_FILE = Path(os.getenv("LM_SMTP_PASS_FILE", "/tmp/.smtp_pass"))


def _gather(db, since):
    feedback_rows = (
        db.query(UserFeedback)
        .filter(UserFeedback.status == "new", UserFeedback.created_at >= since)
        .order_by(UserFeedback.created_at.desc())
        .all()
    )
    incident_rows = (
        db.query(OpsIncident)
        .filter(
            OpsIncident.status == "new",
            OpsIncident.severity.in_(("warn", "error", "critical")),
            OpsIncident.created_at >= since,
        )
        .order_by(OpsIncident.severity.desc(), OpsIncident.created_at.desc())
        .all()
    )
    return feedback_rows, incident_rows


def _format_digest(feedback_rows, incident_rows, period_start, period_end) -> str:
    lines = []
    lines.append(f"Lorcana Monitor — daily health digest")
    lines.append(f"Window: {period_start.isoformat()} → {period_end.isoformat()} UTC")
    lines.append("")
    lines.append(f"Feedback (kind=new): {len(feedback_rows)}")
    lines.append(f"Ops incidents (severity>=warn, status=new): {len(incident_rows)}")
    lines.append("=" * 60)

    if feedback_rows:
        lines.append("")
        lines.append("USER FEEDBACK")
        lines.append("-" * 60)
        by_kind = {}
        for r in feedback_rows:
            by_kind.setdefault(r.kind, []).append(r)
        for kind, rows in sorted(by_kind.items()):
            lines.append(f"\n[{kind}] — {len(rows)}")
            for r in rows[:20]:
                user_part = f"user={r.user_id}" if r.user_id else "anon"
                page = f" page={r.page_url}" if r.page_url else ""
                msg = (r.message or "").strip().replace("\n", " ")
                if len(msg) > 200:
                    msg = msg[:200] + "…"
                lines.append(f"  {r.created_at.strftime('%H:%M')} {user_part}{page}")
                lines.append(f"    > {msg}")
            if len(rows) > 20:
                lines.append(f"  … and {len(rows) - 20} more")

    if incident_rows:
        lines.append("")
        lines.append("OPS INCIDENTS")
        lines.append("-" * 60)
        by_sev = {}
        for r in incident_rows:
            by_sev.setdefault(r.severity, []).append(r)
        for sev in ("critical", "error", "warn"):
            rows = by_sev.get(sev, [])
            if not rows:
                continue
            lines.append(f"\n[{sev.upper()}] — {len(rows)}")
            for r in rows[:20]:
                err = (r.payload or {}).get("error") or ""
                if len(err) > 160:
                    err = err[:160] + "…"
                lines.append(f"  {r.created_at.strftime('%H:%M')} src={r.source}")
                if err:
                    lines.append(f"    > {err}")
            if len(rows) > 20:
                lines.append(f"  … and {len(rows) - 20} more")

    if not feedback_rows and not incident_rows:
        lines.append("")
        lines.append("Nothing to report — system healthy in the last 24h.")

    lines.append("")
    lines.append("--")
    lines.append("Auto-generated by scripts/daily_health_digest.py")
    return "\n".join(lines)


def _send_mail(subject: str, body: str, to_addr: str) -> bool:
    if (os.getenv("LM_SMTP_DISABLED") or "").lower() in ("1", "true", "yes"):
        print(f"[dry] LM_SMTP_DISABLED set; would send to={to_addr} subject={subject}")
        return False
    if not SMTP_PASS_FILE.exists():
        print(f"[error] SMTP password file missing at {SMTP_PASS_FILE}")
        return False
    password = SMTP_PASS_FILE.read_text().strip()
    msg = MIMEText(body)
    msg["Subject"] = subject
    msg["From"] = MAIL_FROM
    msg["To"] = to_addr
    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, timeout=20) as server:
            server.login(MAIL_FROM, password)
            server.send_message(msg)
    except (smtplib.SMTPException, OSError) as exc:
        print(f"[error] SMTP send failed: {exc}")
        return False
    print(f"[ok] mail sent to={to_addr}")
    return True


def _mark_digested(db, feedback_rows, incident_rows):
    now = datetime.now(timezone.utc)
    for r in feedback_rows:
        r.status = "digested"
    for r in incident_rows:
        r.status = "digested"
        r.digested_at = now
    db.commit()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true", help="don't send mail, don't mark digested")
    parser.add_argument("--mail-to", default=MAIL_TO_DEFAULT)
    parser.add_argument("--window-hours", type=int, default=24)
    args = parser.parse_args()

    period_end = datetime.now(timezone.utc)
    period_start = period_end - timedelta(hours=args.window_hours)

    db = SessionLocal()
    try:
        feedback_rows, incident_rows = _gather(db, period_start)
        body = _format_digest(feedback_rows, incident_rows, period_start, period_end)
        n_fb = len(feedback_rows)
        n_inc = len(incident_rows)

        if n_fb == 0 and n_inc == 0:
            subject = f"[lorcana] Daily digest — clean ({period_end.strftime('%Y-%m-%d')})"
        else:
            subject = f"[lorcana] Daily digest — {n_fb} feedback, {n_inc} incidents"

        print("=" * 60)
        print(body)
        print("=" * 60)

        if args.dry_run:
            print("[dry-run] not sending mail, not marking digested")
            return 0

        sent = _send_mail(subject, body, args.mail_to)
        if sent:
            _mark_digested(db, feedback_rows, incident_rows)
            print(f"[ok] marked {n_fb} feedback + {n_inc} incidents as digested")
        return 0
    finally:
        db.close()


if __name__ == "__main__":
    sys.exit(main())
